version: "3"
services:
  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - directus
    depends_on:
      - directus
    #command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - directus
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  database:
    container_name: database
    image: postgis/postgis:15-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - directus
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "INSERT_DB_PASSWORD"
      POSTGRES_DB: "db_name"

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    build:
      context: "./directus/"
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: "aaaa"
      SECRET: "bbbb"
      DB_CLIENT: "pg"
      DB_HOST: "ep-yellow-sunset-15327285.us-west-2.aws.neon.tech"
      DB_PORT: "5432"
      DB_DATABASE: "neondb"
      DB_USER: "binhkid2"
      DB_PASSWORD: "5f0zNLkGITMK"
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      CACHE_REDIS: "redis://cache:6379"
      ADMIN_EMAIL: "binhkid2@gmail.com"
      ADMIN_PASSWORD: "binhkid2@gmail.com"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: "http://localhost:8055"

networks:
  directus:
